export const maps = [
  {
    name: "дом 1",
    size: {
      w: 2880,
      h: 2880,
    },
    coordinates: {
      x: 72,
      y: 72,
    },
    color: "#3b3c36",
    texture: null,
    description: "Это описание для дома",
    id: 0,
    spawn: { x: 1320, y: 2640 },
    objects: [
      {
        x: 48,
        y: 96,
        w: 48,
        h: 2400,
        description: "Левая стена",
        texture: null,
        action: null,
        color: "#91a3b0",
        collision: true,
        sound: null,
      },
      {
        x: 48,
        y: 96,
        w: 2640,
        h: 48,
        description: "Задняя стена",
        texture: null,
        action: null,
        color: "#91a3b0",
        collision: true,
        sound: null,
      },
      {
        x: 2640,
        y: 96,
        w: 48,
        h: 2400,
        description: "Правая стена",
        texture: null,
        action: null,
        color: "#91a3b0",
        collision: true,
        sound: null,
      },
      {
        x: 1600,
        y: 2448,
        w: 1040,
        h: 48,
        description: "Передняя правая стена",
        texture: null,
        action: null,
        color: "#91a3b0",
        collision: true,
        sound: null,
      },
      {
        x: 96,
        y: 2448,
        w: 1200,
        h: 48,
        description: "передняя левая стена",
        texture: null,
        action: null,
        color: "#91a3b0",
        collision: true,
        sound: null,
      },
      {
        x: 1104,
        y: 1008,
        w: 48,
        h: 200,
        description: "Стена коридор/кухня правая 2",
        texture: null,
        action: null,
        color: "#91a3b0",
      },
      {
        x: 1104,
        y: 96,
        w: 48,
        h: 650,
        description: "Стена коридор/кухня правая 1",
        texture: null,
        action: null,
        color: "#91a3b0",
        collision: true,
        sound: null,
      },
      {
        x: 48,
        y: 1200,
        w: 1104,
        h: 48,
        description: "Стена коридор/кухня нижняя",
        texture: null,
        action: null,
        color: "#91a3b0",
        collision: true,
        sound: null,
      },
      {
        x: 1104,
        y: 1248,
        w: 48,
        h: 400,
        description: "Стена коридор/маленькая комната правая 1",
        texture: null,
        action: null,
        color: "#91a3b0",
        collision: true,
        sound: null,
      },
      {
        x: 1104,
        y: 1920,
        w: 48,
        h: 528,
        description: "Стена коридор/маленькая комната правая 2",
        texture: null,
        action: null,
        color: "#91a3b0",
        collision: true,
        sound: null,
      },
      {
        x: 1800,
        y: 2130,
        w: 48,
        h: 315,
        description: "Стена коридор/туалет/ванная комната 1",
        texture: null,
        action: null,
        color: "#91a3b0",
        collision: true,
        sound: null,
      },
      {
        x: 1800,
        y: 1632,
        w: 48,
        h: 240,
        description: "Стена коридор/туалет/ванная комната 2",
        texture: null,
        action: null,
        color: "#91a3b0",
        collision: true,
        sound: null,
      },
      {
        x: 1800,
        y: 1632,
        w: 840,
        h: 48,
        description: "Стена туалет/ванная/ большая комната",
        texture: null,
        action: null,
        color: "#91a3b0",
        collision: true,
        sound: null,
      },
    ],
  },
];
