// Дверной проём 40

export const maps = [
  {
    name: "дом 1",
    size: {
      w: 4800,
      h: 4800,
    },
    coordinates: {
      x: 120,
      y: 120,
    },
    color: "#3b3c36",
    texture: null,
    description: "Это описание для дома",
    id: 0,
    spawn: { x: 2200, y: 4400 },
    objects: [
      {
        x: 80,
        y: 160,
        w: 80,
        h: 4000,
        description: "Левая стена",
        texture: null,
        action: null,
        color: "#91a3b0",
      },
      {
        x: 80,
        y: 160,
        w: 4400,
        h: 80,
        description: "Задняя стена",
        texture: null,
        action: null,
        color: "#91a3b0",
      },
      {
        x: 4400,
        y: 160,
        w: 80,
        h: 4000,
        description: "Правая стена",
        texture: null,
        action: null,
        color: "#91a3b0",
      },
      {
        x: 2380,
        y: 4080,
        w: 2020,
        h: 80,
        description: "Передняя правая стена",
        texture: null,
        action: null,
        color: "#91a3b0",
      },
      {
        x: 160,
        y: 4080,
        w: 1940,
        h: 80,
        description: "передняя левая стена",
        texture: null,
        action: null,
        color: "#91a3b0",
      },
      {
        x: 1840,
        y: 1680,
        w: 80,
        h: 400,
        description: "Стена коридор/кухня правая 2",
        texture: null,
        action: null,
        color: "#91a3b0",
      },
      {
        x: 1840,
        y: 160,
        w: 80,
        h: 1200,
        description: "Стена коридор/кухня правая 1",
        texture: null,
        action: null,
        color: "#91a3b0",
      },
      {
        x: 80,
        y: 2000,
        w: 1840,
        h: 80,
        description: "Стена коридор/кухня нижняя",
        texture: null,
        action: null,
        color: "#91a3b0",
      },
      {
        x: 1840,
        y: 2080,
        w: 80,
        h: 800,
        description: "Стена коридор/маленькая комната правая 1",
        texture: null,
        action: null,
        color: "#91a3b0",
      },
      {
        x: 1840,
        y: 3200,
        w: 80,
        h: 880,
        description: "Стена коридор/маленькая комната правая 2",
        texture: null,
        action: null,
        color: "#91a3b0",
      },
      {
        x: 2560,
        y: 3440,
        w: 80,
        h: 640,
        description: "Стена коридор/туалет/ванная комната 1",
        texture: null,
        action: null,
        color: "#91a3b0",
      },
      {
        x: 2560,
        y: 2720,
        w: 80,
        h: 400,
        description: "Стена коридор/туалет/ванная комната 2",
        texture: null,
        action: null,
        color: "#91a3b0",
      },
      {
        x: 2560,
        y: 2720,
        w: 1840,
        h: 80,
        description: "Стена туалет/ванная/ большая комната",
        texture: null,
        action: null,
        color: "#91a3b0",
      },
    ],
  },
];
